package com.rollonit.convert.helper;

public enum Unit {
    METER, KILOMETER, CENTIMETER, MILLIMETER, MILE, YARD, FOOT, INCH, NAUTICAL_MILE,
    GRAM, KILOGRAM, MILLIGRAM, OUNCE, POUND,
    LITER, MILLILITER, GALLON, QUART, PINT, CUP, TABLESPOON, TEASPOON, FLUID_OUNCE,
    CELSIUS, FAHRENHEIT, KELVIN,
    SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, YEAR
}
